### ISSUE TITLE
Create an automation script to resolve Merge Queues

### ISSUE THREAD

**Issue by sumana2001** [betaoverflow/hi-breaker#88]
A Merge Queue is exactly what it sounds like: it's a queue that you add our branch/Pull-Request to for it to be merged. Merge Queue is a FIFO queue that manages the merge workflow for our Github repository.

It is always easier for developers to directly commit to the master branch. But with the scaling of the project and with the increase in code complexity and contributors the need for branches arises. Merge Queue in simple terms can be thought of as a tool which gives the advantages of directly committing to the master and also the scalability of creating branches. Aside from the obvious convenience of not having to wait for builds to pass to merge, the big reason for using a Merge Queue is that it can help eliminate bad merges and save us both time and money.

Using a merge queue solves that problem by updating any pull request that is not up-to-date with its base branch before it is merged. The update forces the continuous integration system to retest the pull request with the new code from its base branch, catching any potential regression.

Write a Script to add the feature of Merge Queues

**Comment by Aniket762** [comment]
I want to work on it

**Comment by sumana2001** [comment]
@Aniket762, I have assigned you a couple of issues hope you would resolve them soon.
