### ISSUE TITLE
Create a proper documentation of Hi-Breaker

### ISSUE THREAD

**Issue by sumana2001** [betaoverflow/hi-breaker#89]
Hey Contributor,

This particular issue might be a bit confusing when you first look at it. But trust me it isn't. All I want you to do is create a readme which shows what the project is all about. Now, since it is not written anywhere or even the content is properly written how are you supposed to do it? Get in touch with [me](https://www.linkedin.com/in/sumana-basu/). 

We would work together and make sure the ReadMe is along the lines of what I visioned. Let's make this Hacktoberfest not only for contributions but also for interaction.

Thanks,
Sumana

**Comment by Aniket762** [comment]
I'll reach out to you. Can you assign this issue to me?

**Comment by sumana2001** [comment]
@Aniket762 looking forward to talking to you. I plan to maintain this particular repository for Hacktoberfest. Once, you are done with your issues #88 #87 #86 I can actually onboard new contributors. Would be great, if you can resolve the issues `As Soon As Possible` from your end.

**Comment by Aniket762** [comment]
Hey @sumana2001, I will get the 4 issues done by EOD
