### ISSUE TITLE
[Request] Add COC and CG

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/hi-breaker#93]
Hey @sumana2001,

The repository currently misses the Code of Conduct and Contributing guidelines. Thus I am having issues resolving #89. Let me know if I should resolve this issue as well. 

Thanks,
Aniket

**Comment by sumana2001** [comment]
Hey @Aniket762! Thanks for pointing this out. I have assigned you this issue. Please go ahead.
Thanks
